version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - store_test_results:
          path: test-results

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
